name: check_content

on:
  # Intentionally check on all branches, to detect any issues as early as possible
  push:
    branches: [ '*' ]
  pull_request:
    branches: [ '*' ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  check_hub_content:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up Python 3.8
        uses: actions/setup-python@v2
        with:
          python-version: 3.8

      - name: Check the content of the hub
        run: |
          cd .github/scripts
          python3 ./check_content.py
