name: update issues
on:
  schedule:
    - cron: "0 1 * * *"

jobs:
  update_issues:
    runs-on: ubuntu-latest

    steps:
      # ----------------------------------------------------------------------------------
      # Setup
      # ----------------------------------------------------------------------------------
      - uses: actions/checkout@v2

      - uses: ./.github/actions/setup-python
      - uses: ./.github/actions/install-dependencies

      - name: Set up git config
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "github-actions[bot]"
        shell: bash

      # ----------------------------------------------------------------------------------
      # Run scripted updates to Hub Vault Content
      # ----------------------------------------------------------------------------------
      - name: Update theme download counts
        run: |
          cd .github/scripts
          python3 ./update_issues.py --apikey ${{ secrets.GITHUB_TOKEN }}
          git commit -m "Update Issues" -a  || echo "nothing to commit"

      # ----------------------------------------------------------------------------------
      # Finalisation
      # ----------------------------------------------------------------------------------
      # Reference: https://github.com/marketplace/actions/create-pull-request
      - name: Create Pull Request
        id: cpr
        uses: peter-evans/create-pull-request@v3
        with:
          title: Scripted update of Hub content
          assignees: argenos
          labels: |
            scripted update

      - name: Show Pull Request
        run: |
          echo "Pull Request Number - ${{ steps.cpr.outputs.pull-request-number }}"
          echo "Pull Request URL - ${{ steps.cpr.outputs.pull-request-url }}"
